// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kdphniutgqhqlundaqqi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtkcGhuaXV0Z3FocWx1bmRhcXFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1ODkzMDMsImV4cCI6MjA3NDE2NTMwM30.REMRBAA85UDNZAO3siYlOwo04H4VNYlqqo45tU1ud7U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});